---
abstract: 'class-based HTML-centric templating system'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Moose: '0'
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Template-Caribou
provides:
  Template::Caribou:
    file: lib/Template/Caribou.pm
    version: v1.2.2
  Template::Caribou::Files:
    file: lib/Template/Caribou/Files.pm
    version: v1.2.2
  Template::Caribou::Role:
    file: lib/Template/Caribou/Role.pm
    version: v1.2.2
  Template::Caribou::Tags:
    file: lib/Template/Caribou/Tags.pm
    version: v1.2.2
  Template::Caribou::Tags::HTML:
    file: lib/Template/Caribou/Tags/HTML.pm
    version: v1.2.2
  Template::Caribou::Tags::HTML::Extended:
    file: lib/Template/Caribou/Tags/HTML/Extended.pm
    version: v1.2.2
  Template::Caribou::Utils:
    file: lib/Template/Caribou/Utils.pm
    version: v1.2.2
requires:
  Carp: '0'
  Class::Load: '0'
  Exporter::Tiny: '0'
  List::AllUtils: '0'
  Module::Runtime: '0'
  Moose::Exporter: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  MooseX::Role::Parameterized: '0'
  Path::Tiny: '0'
  Ref::Util: '0'
  Text::MultiMarkdown: '0'
  Tie::Handle: '0'
  Try::Tiny: '0'
  XML::Writer: '0'
  experimental: '0'
  overload: '0'
  parent: '0'
  perl: v5.20.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Template-Caribou/issues
  homepage: https://github.com/yanick/Template-Caribou
  repository: https://github.com/yanick/Template-Caribou.git
version: 1.2.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Lisa Hare <lhare@inview.co.uk>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'Paulo Custodio <pauloscustodio@gmail.com>'
  - 'Yanick Champoux <yanick@babyl.ca>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
